language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
 - echo "nothing to be installed yet"

# Scripts to be run as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  # Build
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  # Tagging
  - docker tag reverseproxy ikenjoku/reverseproxy:v1
  - docker tag udagram-api-user ikenjoku/udagram-api-user:v1
  - docker tag udagram-api-feed ikenjoku/udagram-api-feed:v1
  - docker tag udagram-frontend ikenjoku/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ikenjoku/reverseproxy:v1
  - docker push ikenjoku/udagram-api-user:v1
  - docker push ikenjoku/udagram-api-feed:v1
  - docker push ikenjoku/udagram-frontend:v1
